package team.bahor.enums.user;


import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum Permissions {
    ADMIN_CREATE("ADMIN_CREATE"),
    ADMIN_UPDATE("ADMIN_UPDATE"),
    ADMIN_DELETE("ADMIN_DELETE"),
    ADMIN_LIST("ADMIN_LIST"),
    MANAGER_CREATE("MANAGER_CREATE"),
    MANAGER_UPDATE("MANAGER_UPDATE"),
    MANAGER_DELETE("MANAGER_DELETE"),
    MANAGER_LIST("MANAGER_LIST"),
    USER_CREATE("USER_CREATE"),
    USER_UPDATE("USER_UPDATE"),
    USER_DELETE("USER_DELETE"),
    USER_LIST("USER_LIST"),
    PROJECT_CREATE("PROJECT_CREATE"),
    PROJECT_UPDATE("PROJECT_UPDATE"),
    PROJECT_DELETE("PROJECT_DELETE"),
    PROJECT_LIST("PROJECT_LIST");

    private final String code;


}
